import type { Metadata } from "next";
import Script from "next/script";
import localFont from '@next/font/local';

import './styles/globals.scss';


const realHeadPro = localFont({
  src: [
    {
      path: '../../public/fonts/RealHeadPro-SemiLight.ttf',
      weight: '300'
    },
    {
      path: '../../public/fonts/RealHeadPro-Regular.ttf',
      weight: '400'
    },
    {
      path: '../../public/fonts/RealHeadPro-Demibold.ttf',
      weight: '600'
    },
    {
      path: '../../public/fonts/RealHeadPro-Bold.ttf',
      weight: '700'
    }
  ],
  fallback: ['Helvetica', 'ui-sans-serif'],
  display: 'swap'
});


import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <Script src="/scripts/childpage.js" />
        <link rel="stylesheet" href="https://use.typekit.net/opr4dln.css" />
      </head>
      <body>{children}</body>
    </html>
  );
}
